FROM golang:1.20.5-bookworm AS builder

COPY ./ /app

WORKDIR /app

RUN go build -o ./todo .


# FROM gcr.io/distroless/static-debian11
FROM scratch

COPY --from=builder /app/todo /todo
COPY ./configs /configs

EXPOSE 8080

CMD ["/todo"]
